# Generated by Django 4.2.11 on 2024-04-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'fruit',
                'verbose_name_plural': 'fruits',
                'db_table': 'fruit',
            },
        ),
    ]
